cleanstone:
  subServer: false

  mainServerAddress: 127.0.0.1
  mainServerPort: 25564

  requiredSubServers:
   - 127.0.0.2

  port: 25564
  address: 0.0.0.0

minecraft:
  port: 25565
  address: 0.0.0.0
  onlineMode: false